server:
  port: 8080
spring:
  application:
    name: customer-service
  config:
    import:
      - optional:configserver:http://ms-configserver:8888
  data:
    mongodb:
      uri: mongodb://db_customer:27017/db_customer
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-customer: /api/v1/customers
  path-customerType: /api/v1/customerType