spring:
  config:
    import:
    - optional:configserver:http://ms-configserver:8888
  application:
    name: customer-service
  data:
    mongodb:
      database: db_customer
      host: localhost
      port: 27017
server:
  port: 8080
management:
  endpoint:
    web:
      exposure:
        include: "*"
message:
  path-customer: /api/v1/customers
  path-customerType: /api/v1/customerType